version: '3'

networks:
  nginx:
   driver: bridge

services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx
      - ./ssl:/etc/ssl/sites
      - ~/projects:/var/www/vhosts
    build:
      context: ./src
      dockerfile: nginx.dockerfile
    networks:
      - nginx

  laravel:
    build:
      context: ./src
      dockerfile: php7.4.dockerfile
    container_name: laravel
    restart: unless-stopped
    volumes:
      - ~/projects:/var/www/vhosts
    expose:
      - "9000"
    networks:
      - nginx

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - nginx