version: '3'

services:

  ### Services
  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: cookie
      MYSQL_USER: cookie
      MYSQL_PASSWORD: donut
      MYSQL_ROOT_PASSWORD: donut
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  nginx:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  ### Tools
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports: 
      - "8090:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: cookie
      PMA_PASSWORD: donut
      UPLOAD_LIMIT: 2G
      VIRTUAL_HOST: phpmyadmin.test

  ### Sites
  laravel:
    tty: true
    build:
      context: ./docker
      dockerfile: php.dockerfile
    environment:
      DB_HOST: mysql
      DB_USERNAME: cookie
      DB_DATABASE: cookie
      DB_PASSWORD: donut
      VIRTUAL_HOST: laravel.test
    depends_on:
      - db
    expose:
      - 80
    volumes:
      - ./app:/var/www/html