version: '3'

services:
  ### Services
  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: cookie
      MYSQL_PASSWORD: donut
      MYSQL_ROOT_PASSWORD: donut

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/etc/nginx/conf.d/:/etc/nginx/conf.d/

  ### Tools
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "3305:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: cookie
      PMA_PASSWORD: donut
      UPLOAD_LIMIT: 2G

  ### Sites
  laravel:
    env_file:
      - ./.env
    tty: true
    build:
      args:
        user: "${UID}"
        uid: "${UID}"
      context: ./docker/php
      dockerfile: Dockerfile
    user: "${UID}:${GID}"
    depends_on:
      - db
    expose:
      - 9000
    volumes:
      - ./:/var/www/html
