version: '3'

networks:
  nginx:
   driver: bridge

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: cookie
      MYSQL_USER: cookie
      MYSQL_PASSWORD: donut
      MYSQL_ROOT_PASSWORD: donut
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  laravel:
    tty: true
    image: docker.io/bitnami/laravel:7-debian-10
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=cookie
      - DB_DATABASE=cookie
      - DB_PASSWORD=donut
    depends_on:
      - db
    ports:
      - 8080:3000
    volumes:
      - ./app:/app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports: 
      - "8090:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: cookie
      PMA_PASSWORD: donut
      UPLOAD_LIMIT: 2G  