version: '3'

services:

  ### Services
  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: cookie
      MYSQL_PASSWORD: donut
      MYSQL_ROOT_PASSWORD: donut

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/etc/nginx/conf.d/laravel.test.conf:/etc/nginx/conf.d/laravel.test.conf

  ### Tools
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports: 
      - "3305:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: cookie
      PMA_PASSWORD: donut
      UPLOAD_LIMIT: 2G

  ### Sites
  laravel:
    tty: true
    build:
      args:
        user: 1000
        uid: 1000
      context: ./docker/php
      dockerfile: Dockerfile
    user: "${UID_GID}" # Remember to set this when doc up'ing: `UID_GID="$(id -u):$(id -g)" docker-compose up -d`
    environment:
      DB_HOST: mysql
      DB_USERNAME: root
      DB_DATABASE: cookie
      DB_PASSWORD: donut
    depends_on:
      - db
    expose:
      - 9000
    volumes:
      - ./app:/var/www/html